import argparse
import json
from pathlib import Path
from typing import Any

try:
    from scripts.command_from_dataset import maybe_add_multi, maybe_add_pair, to_powershell_command
except ModuleNotFoundError:
    from command_from_dataset import maybe_add_multi, maybe_add_pair, to_powershell_command


def main() -> None:
    parser = argparse.ArgumentParser(description="Print a make_model.py command from a model summary JSON.")
    parser.add_argument("summary", type=Path, help="Path to a *_summary.json file generated by make_model.py.")
    args = parser.parse_args()

    print(build_command(args.summary))


def build_command(summary_path: Path) -> str:
    summary = json.loads(summary_path.read_text(encoding="utf-8-sig"))
    options = summary.get("options")
    if not isinstance(options, dict):
        raise ValueError(f"{summary_path} does not contain an options object")

    parts = [
        ".\\.venv\\Scripts\\python.exe",
        "make_model.py",
        "--area",
        _require_string(options, "area"),
        "--dem",
        _require_string(options, "dem"),
        "--out",
        _require_string(options, "out"),
    ]

    buildings = options.get("buildings")
    if isinstance(buildings, str) and buildings.strip():
        parts.extend(["--buildings", buildings])

    maybe_add_pair(parts, "--target-crs", options.get("target_crs"))
    maybe_add_pair(parts, "--area-crs", options.get("area_crs"))
    maybe_add_pair(parts, "--building-crs", options.get("building_crs"))
    maybe_add_pair(parts, "--dem-crs", options.get("dem_crs"))
    _maybe_add_number(parts, "--terrain-resolution", options.get("terrain_resolution"))
    _maybe_add_number(parts, "--terrain-smoothing-iterations", options.get("terrain_smoothing_iterations"))
    _maybe_add_number(parts, "--terrain-smoothing-factor", options.get("terrain_smoothing_factor"))
    _maybe_add_number(parts, "--base-thickness", options.get("base_thickness"))
    _maybe_add_number(parts, "--default-floor-height", options.get("default_floor_height"))
    _maybe_add_number(parts, "--default-building-height", options.get("default_building_height"))
    _maybe_add_number(parts, "--min-building-area", options.get("min_building_area"))
    _maybe_add_number(parts, "--simplify-tolerance", options.get("simplify_tolerance"))
    _maybe_add_number(parts, "--model-scale", options.get("model_scale"))
    _maybe_add_number(parts, "--base-plate-thickness", options.get("base_plate_thickness"))
    _maybe_add_number(parts, "--base-plate-margin", options.get("base_plate_margin"))
    _maybe_add_number(parts, "--max-area-km2", options.get("max_area_km2"))
    _maybe_add_number(parts, "--building-diagnostics-limit", options.get("building_diagnostics_limit"))
    _maybe_add_number(parts, "--z-scale", options.get("z_scale"))
    maybe_add_pair(parts, "--building-base-mode", options.get("building_base_mode"))
    maybe_add_multi(parts, "--height-field", options.get("height_fields"))
    maybe_add_multi(parts, "--floor-field", options.get("floor_fields"))
    maybe_add_multi(parts, "--export-format", options.get("export_formats"))

    if options.get("interpolate_nodata") is True:
        parts.append("--interpolate-nodata")
    if options.get("separate") is True:
        parts.append("--separate")
    if options.get("preview") is True:
        parts.append("--preview")

    return to_powershell_command(parts)


def _require_string(options: dict[str, Any], key: str) -> str:
    value = options.get(key)
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"summary options.{key} must be a non-empty string")
    return value


def _maybe_add_number(parts: list[str], flag: str, value: object) -> None:
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        parts.extend([flag, str(value)])


if __name__ == "__main__":
    main()
