import argparse
import json
import math
from pathlib import Path
from typing import Any


def main() -> None:
    parser = argparse.ArgumentParser(description="Validate print readiness from a *_summary.json mesh report.")
    parser.add_argument("summary", type=Path, help="Path to *_summary.json generated by make_model.py.")
    parser.add_argument("--require-watertight", action="store_true", help="Fail when mesh is not watertight.")
    parser.add_argument(
        "--max-non-manifold-edges",
        type=int,
        default=0,
        help="Maximum allowed non-manifold edge count (default: 0).",
    )
    parser.add_argument(
        "--max-degenerate-faces",
        type=int,
        default=0,
        help="Maximum allowed degenerate face count (default: 0).",
    )
    parser.add_argument("--min-dimension", type=float, default=None, help="Minimum allowed bbox side length.")
    parser.add_argument("--max-dimension", type=float, default=None, help="Maximum allowed bbox side length.")
    parser.add_argument("--min-volume", type=float, default=None, help="Minimum required mesh volume.")
    parser.add_argument(
        "--format",
        choices=("json", "text"),
        default="json",
        help="Output format (default: json).",
    )
    args = parser.parse_args()

    summary = json.loads(args.summary.read_text(encoding="utf-8-sig"))
    report = validate_summary(
        summary,
        require_watertight=args.require_watertight,
        max_non_manifold_edges=args.max_non_manifold_edges,
        max_degenerate_faces=args.max_degenerate_faces,
        min_dimension=args.min_dimension,
        max_dimension=args.max_dimension,
        min_volume=args.min_volume,
    )

    if args.format == "text":
        print(format_text_report(report))
    else:
        print(json.dumps(report, indent=2))

    if not report["passed"]:
        raise SystemExit(1)


def validate_summary(
    summary: dict[str, Any],
    *,
    require_watertight: bool,
    max_non_manifold_edges: int,
    max_degenerate_faces: int,
    min_dimension: float | None,
    max_dimension: float | None,
    min_volume: float | None,
) -> dict[str, Any]:
    mesh_quality = summary.get("mesh_quality")
    if not isinstance(mesh_quality, dict):
        raise ValueError("summary does not contain a mesh_quality object")

    checks: list[dict[str, Any]] = []

    if require_watertight:
        watertight = mesh_quality.get("is_watertight")
        checks.append(_result("watertight", watertight is True, actual=watertight, expected=True))

    non_manifold_edges = _as_int(mesh_quality.get("non_manifold_edge_count"))
    checks.append(
        _result(
            "max_non_manifold_edges",
            non_manifold_edges is not None and non_manifold_edges <= max_non_manifold_edges,
            actual=non_manifold_edges,
            expected=max_non_manifold_edges,
        )
    )

    degenerate_faces = _as_int(mesh_quality.get("degenerate_face_count"))
    checks.append(
        _result(
            "max_degenerate_faces",
            degenerate_faces is not None and degenerate_faces <= max_degenerate_faces,
            actual=degenerate_faces,
            expected=max_degenerate_faces,
        )
    )

    dimensions = _dimensions(mesh_quality.get("bounds"))
    if min_dimension is not None:
        smallest = min(dimensions) if dimensions is not None else None
        checks.append(
            _result(
                "min_dimension",
                smallest is not None and smallest >= min_dimension,
                actual=smallest,
                expected=min_dimension,
            )
        )
    if max_dimension is not None:
        largest = max(dimensions) if dimensions is not None else None
        checks.append(
            _result(
                "max_dimension",
                largest is not None and largest <= max_dimension,
                actual=largest,
                expected=max_dimension,
            )
        )

    if min_volume is not None:
        volume = _as_float(mesh_quality.get("volume"))
        checks.append(_result("min_volume", volume is not None and volume >= min_volume, actual=volume, expected=min_volume))

    passed = all(item["passed"] for item in checks)
    return {
        "passed": passed,
        "summary_path": summary.get("summary_path"),
        "thresholds": {
            "require_watertight": require_watertight,
            "max_non_manifold_edges": max_non_manifold_edges,
            "max_degenerate_faces": max_degenerate_faces,
            "min_dimension": min_dimension,
            "max_dimension": max_dimension,
            "min_volume": min_volume,
        },
        "checks": checks,
    }


def format_text_report(report: dict[str, Any]) -> str:
    lines = [f"PASS={report['passed']}"]
    for check in report["checks"]:
        status = "PASS" if check["passed"] else "FAIL"
        lines.append(f"{status:4} {check['name']}: actual={check['actual']} expected={check['expected']}")
    return "\n".join(lines)


def _result(name: str, passed: bool, *, actual: Any, expected: Any) -> dict[str, Any]:
    return {"name": name, "passed": passed, "actual": actual, "expected": expected}


def _dimensions(bounds: Any) -> tuple[float, float, float] | None:
    if not isinstance(bounds, (list, tuple)) or len(bounds) != 2:
        return None
    low, high = bounds
    if not isinstance(low, (list, tuple)) or not isinstance(high, (list, tuple)):
        return None
    if len(low) != 3 or len(high) != 3:
        return None
    dims: list[float] = []
    for min_v, max_v in zip(low, high):
        min_f = _as_float(min_v)
        max_f = _as_float(max_v)
        if min_f is None or max_f is None:
            return None
        dims.append(max_f - min_f)
    return (dims[0], dims[1], dims[2])


def _as_int(value: Any) -> int | None:
    if isinstance(value, bool):
        return None
    if isinstance(value, int):
        return value
    if isinstance(value, float) and math.isfinite(value) and value.is_integer():
        return int(value)
    return None


def _as_float(value: Any) -> float | None:
    if isinstance(value, bool):
        return None
    if isinstance(value, (int, float)):
        value = float(value)
        if math.isfinite(value):
            return value
    return None


if __name__ == "__main__":
    main()
