import argparse
import json
import math
import shlex
import subprocess
from pathlib import Path
from typing import Any

DEFAULT_PROFILE = "default"
PROFILES: dict[str, dict[str, Any]] = {
    "default": {
        "require_watertight": False,
        "max_non_manifold_edges": 0,
        "max_degenerate_faces": 0,
        "min_dimension": None,
        "max_dimension": None,
        "min_volume": None,
        "min_base_thickness": None,
        "min_wall_thickness": None,
    },
    "fdm": {
        "require_watertight": True,
        "max_non_manifold_edges": 0,
        "max_degenerate_faces": 0,
        "min_dimension": 5.0,
        "max_dimension": 220.0,
        "min_volume": 1.0,
        "min_base_thickness": 1.2,
        "min_wall_thickness": 0.8,
    },
    "resin": {
        "require_watertight": True,
        "max_non_manifold_edges": 0,
        "max_degenerate_faces": 0,
        "min_dimension": 3.0,
        "max_dimension": 140.0,
        "min_volume": 0.2,
        "min_base_thickness": 0.8,
        "min_wall_thickness": 0.4,
    },
}


def main() -> None:
    parser = argparse.ArgumentParser(description="Validate print readiness from a *_summary.json mesh report.")
    parser.add_argument("summary", type=Path, help="Path to *_summary.json generated by make_model.py.")
    parser.add_argument(
        "--slicer-profile",
        choices=tuple(PROFILES.keys()),
        default=DEFAULT_PROFILE,
        help="Local slicer-readiness threshold profile (no external slicer required).",
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Alias for --slicer-profile fdm unless profile was explicitly set.",
    )
    parser.add_argument("--require-watertight", action="store_true", help="Fail when mesh is not watertight.")
    parser.add_argument(
        "--max-non-manifold-edges",
        type=int,
        default=None,
        help="Maximum allowed non-manifold edge count (default: 0).",
    )
    parser.add_argument(
        "--max-degenerate-faces",
        type=int,
        default=None,
        help="Maximum allowed degenerate face count (default: 0).",
    )
    parser.add_argument("--min-dimension", type=float, default=None, help="Minimum allowed bbox side length.")
    parser.add_argument("--max-dimension", type=float, default=None, help="Maximum allowed bbox side length.")
    parser.add_argument("--min-volume", type=float, default=None, help="Minimum required mesh volume.")
    parser.add_argument(
        "--format",
        choices=("json", "text"),
        default="json",
        help="Output format (default: json).",
    )
    parser.add_argument(
        "--slicer-check-cmd",
        default=None,
        help="Optional external slicer check command template. Supports {summary} and {model} placeholders.",
    )
    parser.add_argument(
        "--model-path",
        type=Path,
        default=None,
        help="Model file path used for {model} in --slicer-check-cmd.",
    )
    parser.add_argument(
        "--slicer-timeout-seconds",
        type=float,
        default=120.0,
        help="Timeout for the external slicer check command (default: 120).",
    )
    parser.add_argument(
        "--include-slicer-template",
        action="store_true",
        help="Include a suggested slicer-check command template in the report.",
    )
    args = parser.parse_args()

    summary_path = args.summary.resolve()
    summary = json.loads(summary_path.read_text(encoding="utf-8-sig"))
    profile_name, thresholds = _effective_thresholds(args)
    report = validate_summary(
        summary,
        profile_name=profile_name,
        **thresholds,
    )
    slicer_context = _build_slicer_context(summary_path, args.model_path)
    if args.include_slicer_template:
        report["slicer_check_template"] = slicer_check_template(slicer_context)
    if args.slicer_check_cmd:
        report["slicer_check"] = run_slicer_check(
            args.slicer_check_cmd,
            context=slicer_context,
            timeout_seconds=args.slicer_timeout_seconds,
        )
        report["passed"] = report["passed"] and report["slicer_check"]["passed"]

    if args.format == "text":
        print(format_text_report(report))
    else:
        print(json.dumps(report, indent=2))

    if not report["passed"]:
        raise SystemExit(1)


def validate_summary(
    summary: dict[str, Any],
    *,
    profile_name: str = DEFAULT_PROFILE,
    require_watertight: bool,
    max_non_manifold_edges: int,
    max_degenerate_faces: int,
    min_dimension: float | None,
    max_dimension: float | None,
    min_volume: float | None,
    min_base_thickness: float | None = None,
    min_wall_thickness: float | None = None,
) -> dict[str, Any]:
    mesh_quality = summary.get("mesh_quality")
    if not isinstance(mesh_quality, dict):
        raise ValueError("summary does not contain a mesh_quality object")

    checks: list[dict[str, Any]] = []

    if require_watertight:
        watertight = mesh_quality.get("is_watertight")
        checks.append(_result("watertight", watertight is True, actual=watertight, expected=True))

    non_manifold_edges = _as_int(mesh_quality.get("non_manifold_edge_count"))
    checks.append(
        _result(
            "max_non_manifold_edges",
            non_manifold_edges is not None and non_manifold_edges <= max_non_manifold_edges,
            actual=non_manifold_edges,
            expected=max_non_manifold_edges,
        )
    )

    degenerate_faces = _as_int(mesh_quality.get("degenerate_face_count"))
    checks.append(
        _result(
            "max_degenerate_faces",
            degenerate_faces is not None and degenerate_faces <= max_degenerate_faces,
            actual=degenerate_faces,
            expected=max_degenerate_faces,
        )
    )

    dimensions = _dimensions(mesh_quality.get("bounds"))
    if min_dimension is not None:
        smallest = min(dimensions) if dimensions is not None else None
        checks.append(
            _result(
                "min_dimension",
                smallest is not None and smallest >= min_dimension,
                actual=smallest,
                expected=min_dimension,
            )
        )
    if max_dimension is not None:
        largest = max(dimensions) if dimensions is not None else None
        checks.append(
            _result(
                "max_dimension",
                largest is not None and largest <= max_dimension,
                actual=largest,
                expected=max_dimension,
            )
        )

    if min_volume is not None:
        volume = _as_float(mesh_quality.get("volume"))
        checks.append(_result("min_volume", volume is not None and volume >= min_volume, actual=volume, expected=min_volume))

    # Optional hints can come from mesh_quality or top-level summary.
    base_thickness = _hint_value(summary, mesh_quality, "base_thickness", "base_thickness_hint", "min_base_thickness")
    if min_base_thickness is not None:
        checks.append(
            _result(
                "min_base_thickness",
                base_thickness is not None and base_thickness >= min_base_thickness,
                actual=base_thickness,
                expected=min_base_thickness,
            )
        )

    wall_thickness = _hint_value(summary, mesh_quality, "wall_thickness", "wall_thickness_hint", "min_wall_thickness")
    if min_wall_thickness is not None:
        checks.append(
            _result(
                "min_wall_thickness",
                wall_thickness is not None and wall_thickness >= min_wall_thickness,
                actual=wall_thickness,
                expected=min_wall_thickness,
            )
        )

    passed = all(item["passed"] for item in checks)
    return {
        "passed": passed,
        "profile": profile_name,
        "summary_path": summary.get("summary_path"),
        "thresholds": {
            "require_watertight": require_watertight,
            "max_non_manifold_edges": max_non_manifold_edges,
            "max_degenerate_faces": max_degenerate_faces,
            "min_dimension": min_dimension,
            "max_dimension": max_dimension,
            "min_volume": min_volume,
            "min_base_thickness": min_base_thickness,
            "min_wall_thickness": min_wall_thickness,
        },
        "checks": checks,
    }


def format_text_report(report: dict[str, Any]) -> str:
    lines = [f"PASS={report['passed']}", f"PROFILE={report.get('profile', DEFAULT_PROFILE)}"]
    for check in report["checks"]:
        status = "PASS" if check["passed"] else "FAIL"
        label = check.get("label", check["name"])
        recommendation = check.get("recommendation")
        line = f"{status:4} {label}: actual={check['actual']} expected={check['expected']}"
        if recommendation:
            line += f" | {recommendation}"
        lines.append(line)
    slicer_check = report.get("slicer_check")
    if isinstance(slicer_check, dict):
        lines.append(
            "SLICER_CHECK="
            + ("PASS" if slicer_check.get("passed") else "FAIL")
            + f" command={slicer_check.get('command')}"
        )
        if slicer_check.get("error"):
            lines.append(f"SLICER_ERROR={slicer_check['error']}")
    template = report.get("slicer_check_template")
    if isinstance(template, str):
        lines.append(f"SLICER_TEMPLATE={template}")
    return "\n".join(lines)


def _result(name: str, passed: bool, *, actual: Any, expected: Any) -> dict[str, Any]:
    return {
        "name": name,
        "passed": passed,
        "actual": actual,
        "expected": expected,
        "label": CHECK_META.get(name, {}).get("label", name),
        "recommendation": CHECK_META.get(name, {}).get("recommendation"),
    }


CHECK_META: dict[str, dict[str, str]] = {
    "watertight": {
        "label": "Mesh is watertight",
        "recommendation": "Repair open boundaries before slicing.",
    },
    "max_non_manifold_edges": {
        "label": "Non-manifold edges within limit",
        "recommendation": "Run mesh repair to remove non-manifold edges.",
    },
    "max_degenerate_faces": {
        "label": "Degenerate faces within limit",
        "recommendation": "Remove zero-area faces before export.",
    },
    "min_dimension": {
        "label": "Smallest bbox dimension above minimum",
        "recommendation": "Scale up or increase model footprint.",
    },
    "max_dimension": {
        "label": "Largest bbox dimension below maximum",
        "recommendation": "Scale down to fit printer build volume.",
    },
    "min_volume": {
        "label": "Volume above minimum",
        "recommendation": "Increase height/base thickness to avoid fragile print.",
    },
    "min_base_thickness": {
        "label": "Base thickness hint above minimum",
        "recommendation": "Increase base thickness for bed adhesion.",
    },
    "min_wall_thickness": {
        "label": "Wall thickness hint above minimum",
        "recommendation": "Increase wall/feature thickness to match nozzle/resin limits.",
    },
}


def _dimensions(bounds: Any) -> tuple[float, float, float] | None:
    if not isinstance(bounds, (list, tuple)) or len(bounds) != 2:
        return None
    low, high = bounds
    if not isinstance(low, (list, tuple)) or not isinstance(high, (list, tuple)):
        return None
    if len(low) != 3 or len(high) != 3:
        return None
    dims: list[float] = []
    for min_v, max_v in zip(low, high):
        min_f = _as_float(min_v)
        max_f = _as_float(max_v)
        if min_f is None or max_f is None:
            return None
        dims.append(max_f - min_f)
    return (dims[0], dims[1], dims[2])


def _as_int(value: Any) -> int | None:
    if isinstance(value, bool):
        return None
    if isinstance(value, int):
        return value
    if isinstance(value, float) and math.isfinite(value) and value.is_integer():
        return int(value)
    return None


def _as_float(value: Any) -> float | None:
    if isinstance(value, bool):
        return None
    if isinstance(value, (int, float)):
        value = float(value)
        if math.isfinite(value):
            return value
    return None


def _effective_thresholds(args: argparse.Namespace) -> tuple[str, dict[str, Any]]:
    profile_name = args.slicer_profile
    if args.strict and profile_name == DEFAULT_PROFILE:
        profile_name = "fdm"
    profile = dict(PROFILES[profile_name])

    # CLI flags can override profile defaults.
    if args.require_watertight:
        profile["require_watertight"] = True
    if args.max_non_manifold_edges is not None:
        profile["max_non_manifold_edges"] = args.max_non_manifold_edges
    if args.max_degenerate_faces is not None:
        profile["max_degenerate_faces"] = args.max_degenerate_faces
    if args.min_dimension is not None:
        profile["min_dimension"] = args.min_dimension
    if args.max_dimension is not None:
        profile["max_dimension"] = args.max_dimension
    if args.min_volume is not None:
        profile["min_volume"] = args.min_volume
    return profile_name, profile


def _hint_value(summary: dict[str, Any], mesh_quality: dict[str, Any], *keys: str) -> float | None:
    for source in (mesh_quality, summary):
        for key in keys:
            value = _as_float(source.get(key))
            if value is not None:
                return value
    return None


def _build_slicer_context(summary_path: Path, model_path: Path | None) -> dict[str, str]:
    resolved_model = model_path.resolve() if model_path is not None else _infer_model_path(summary_path)
    return {
        "summary": str(summary_path),
        "model": str(resolved_model) if resolved_model is not None else "",
    }


def _infer_model_path(summary_path: Path) -> Path | None:
    if summary_path.name.endswith("_summary.json"):
        candidate = summary_path.with_name(summary_path.name[: -len("_summary.json")] + ".stl")
        if candidate.exists():
            return candidate.resolve()
    return None


def slicer_check_template(context: dict[str, str]) -> str:
    return (
        'prusa-slicer-console.exe --export-gcode --load "printer_config.ini" '
        '--output "output.gcode" "{model}"'
    ).format_map(context)


def run_slicer_check(command_template: str, *, context: dict[str, str], timeout_seconds: float) -> dict[str, Any]:
    try:
        command = command_template.format_map(context)
    except KeyError as exc:
        return {
            "passed": False,
            "command_template": command_template,
            "error": f"unknown placeholder: {exc}",
        }

    if "{model}" in command_template and not context.get("model"):
        return {
            "passed": False,
            "command_template": command_template,
            "error": "model path is required for {model}; pass --model-path or place <name>.stl next to *_summary.json",
        }

    try:
        args = shlex.split(command, posix=False)
    except ValueError as exc:
        return {
            "passed": False,
            "command": command,
            "error": f"invalid command syntax: {exc}",
        }

    try:
        completed = subprocess.run(args, capture_output=True, text=True, timeout=timeout_seconds, check=False)
    except FileNotFoundError as exc:
        return {
            "passed": False,
            "command": command,
            "error": f"command not found: {exc}",
        }
    except OSError as exc:
        return {
            "passed": False,
            "command": command,
            "error": f"failed to run command: {exc}",
        }

    return {
        "passed": completed.returncode == 0,
        "command": command,
        "returncode": completed.returncode,
        "stdout": completed.stdout,
        "stderr": completed.stderr,
    }


if __name__ == "__main__":
    main()
